language: node_js

node_js:
  - 10.9.0

before_script:
  - npm install grunt-cli -g

script:
  - grunt

jobs:
  include:
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true